"""Interactive setup wizard for ActionPulse.

Collects credentials and config via terminal prompts, generates:
  - ~/.config/actionpulse/env  (KEY=value, systemd-compatible)
  - configs/config.yaml        (copy of example with user values applied)

No text editor needed.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Optional

import typer
import yaml

from digest_core.config import PROJECT_ROOT

ENV_DIR = Path.home() / ".config" / "actionpulse"
ENV_PATH = ENV_DIR / "env"
CONFIG_EXAMPLE = PROJECT_ROOT / "configs" / "config.example.yaml"
CONFIG_USER = PROJECT_ROOT / "configs" / "config.yaml"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_existing_env() -> dict[str, str]:
    """Read existing env file into dict."""
    values: dict[str, str] = {}
    if not ENV_PATH.exists():
        return values
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            values[key.strip()] = val.strip()
    return values


def _read_existing_config() -> dict:
    """Read existing config.yaml (or example) into dict."""
    path = CONFIG_USER if CONFIG_USER.exists() else CONFIG_EXAMPLE
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _derive_from_email(email: str) -> dict[str, str]:
    """Derive EWS fields from corp email address.

    ivan.petrov@megacorp.ru ->
        user_login: ivan.petrov
        user_domain: megacorp.ru
        default_ews_endpoint: https://owa.megacorp.ru/EWS/Exchange.asmx
        aliases: ["Ivan", "Petrov", "ivan.petrov@megacorp.ru", "ivan.petrov"]
    """
    login, _, domain = email.partition("@")
    parts = re.split(r"[._-]", login)
    aliases = [p.capitalize() for p in parts if len(p) > 1]
    aliases.extend([email, login])

    return {
        "user_login": login,
        "user_domain": domain,
        "default_ews_endpoint": f"https://owa.{domain}/EWS/Exchange.asmx",
        "aliases": aliases,
    }


def _write_env_file(values: dict[str, str]) -> Path:
    """Write env file in systemd-compatible KEY=value format."""
    ENV_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "# ActionPulse environment — generated by 'python -m digest_core.cli setup'",
        "# Format: KEY=value (no export, no quotes) — works with systemd and bash",
        "",
        "# === Required ===",
        "",
    ]
    required_keys = [
        "EWS_PASSWORD",
        "EWS_USER_UPN",
        "EWS_ENDPOINT",
        "LLM_TOKEN",
        "LLM_ENDPOINT",
        "MM_WEBHOOK_URL",
    ]
    for key in required_keys:
        if key in values:
            lines.append(f"{key}={values[key]}")
    lines.append("")
    lines.append("# === Optional ===")
    lines.append("")
    lines.append("# DIGEST_CONFIG_PATH=/path/to/config.yaml")
    lines.append("# DIGEST_OUT_DIR=/custom/out")
    lines.append("# DIGEST_STATE_DIR=/custom/state")
    lines.append("# DIGEST_LOG_LEVEL=INFO")
    lines.append("")

    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    os.chmod(ENV_PATH, 0o600)
    return ENV_PATH


def _write_config_yaml(
    user_upn: str,
    ews_endpoint: str,
    llm_endpoint: str,
    derived: dict[str, str],
    verify_ca: Optional[str],
) -> Path:
    """Generate configs/config.yaml from example with user values applied."""
    if not CONFIG_EXAMPLE.exists():
        raise FileNotFoundError(f"Config example not found: {CONFIG_EXAMPLE}")

    with open(CONFIG_EXAMPLE, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    # Apply user values
    ews = config.get("ews", {})
    ews["endpoint"] = ews_endpoint
    ews["user_upn"] = user_upn
    ews["user_login"] = derived["user_login"]
    ews["user_domain"] = derived["user_domain"]
    ews["user_aliases"] = derived["aliases"]
    if verify_ca:
        ews["verify_ca"] = verify_ca
    else:
        ews.pop("verify_ca", None)
    config["ews"] = ews

    llm = config.get("llm", {})
    llm["endpoint"] = llm_endpoint
    config["llm"] = llm

    CONFIG_USER.parent.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_USER, "w", encoding="utf-8") as f:
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    return CONFIG_USER


# ---------------------------------------------------------------------------
# Main wizard
# ---------------------------------------------------------------------------


def run_setup() -> None:
    """Interactive setup: 6 questions, 0 text editors."""

    typer.echo("")
    typer.echo("═══ ActionPulse Setup ═══")
    typer.echo("")
    typer.echo("Ответьте на несколько вопросов. Секреты не отображаются при вводе.")
    typer.echo("Для значений по умолчанию — нажмите Enter.")
    typer.echo("")

    # Read existing values for defaults
    existing_env = _read_existing_env()
    existing_cfg = _read_existing_config()

    # ── 1. Corp email ──
    default_upn = (
        existing_env.get("EWS_USER_UPN") or existing_cfg.get("ews", {}).get("user_upn") or ""
    )
    user_upn = typer.prompt(
        "1/6  Корпоративный email (login@corp-domain.ru)",
        default=default_upn or None,
    )
    user_upn = user_upn.strip()

    if "@" not in user_upn:
        typer.echo("⚠ Email должен содержать @. Попробуйте снова.", err=True)
        raise typer.Exit(1)

    derived = _derive_from_email(user_upn)
    typer.echo(f"  → login: {derived['user_login']}, domain: {derived['user_domain']}")
    typer.echo(f"  → aliases: {derived['aliases']}")
    typer.echo("")

    # ── 2. EWS endpoint ──
    default_ews = (
        existing_env.get("EWS_ENDPOINT")
        or existing_cfg.get("ews", {}).get("endpoint")
        or derived["default_ews_endpoint"]
    )
    ews_endpoint = typer.prompt(
        "2/6  EWS endpoint URL",
        default=default_ews,
    ).strip()
    typer.echo("")

    # ── 3. EWS password ──
    ews_password = typer.prompt(
        "3/6  EWS пароль (Exchange)",
        hide_input=True,
        confirmation_prompt=True,
    )
    typer.echo("")

    # ── 4. LLM endpoint ──
    default_llm = (
        existing_env.get("LLM_ENDPOINT") or existing_cfg.get("llm", {}).get("endpoint") or ""
    )
    llm_endpoint = typer.prompt(
        "4/6  LLM Gateway endpoint URL",
        default=default_llm or None,
    ).strip()
    typer.echo("")

    # ── 5. LLM token ──
    llm_token = typer.prompt(
        "5/6  LLM токен (Bearer)",
        hide_input=True,
        confirmation_prompt=True,
    )
    typer.echo("")

    # ── 6. Mattermost webhook ──
    default_mm = existing_env.get("MM_WEBHOOK_URL", "")
    mm_webhook = typer.prompt(
        "6/6  Mattermost webhook URL",
        default=default_mm or None,
    ).strip()
    typer.echo("")

    # ── Optional: CA certificate ──
    verify_ca: Optional[str] = None
    if typer.confirm("Нужен кастомный CA-сертификат для EWS?", default=False):
        verify_ca = typer.prompt("  Путь к CA-сертификату (.pem)").strip()
        if verify_ca and not Path(verify_ca).exists():
            typer.echo(f"  ⚠ Файл не найден: {verify_ca} (сохраняю путь как есть)")
    typer.echo("")

    # ── Write files ──
    typer.echo("Генерация файлов...")

    env_values = {
        "EWS_PASSWORD": ews_password,
        "EWS_USER_UPN": user_upn,
        "EWS_ENDPOINT": ews_endpoint,
        "LLM_TOKEN": llm_token,
        "LLM_ENDPOINT": llm_endpoint,
        "MM_WEBHOOK_URL": mm_webhook,
    }
    env_path = _write_env_file(env_values)
    typer.echo(f"  ✓ {env_path}  (chmod 600)")

    config_path = _write_config_yaml(
        user_upn=user_upn,
        ews_endpoint=ews_endpoint,
        llm_endpoint=llm_endpoint,
        derived=derived,
        verify_ca=verify_ca,
    )
    typer.echo(f"  ✓ {config_path}")
    typer.echo("")

    # ── Load env into current process ──
    for key, val in env_values.items():
        os.environ[key] = val

    # ── Summary ──
    typer.echo("═══ Готово ═══")
    typer.echo("")
    typer.echo("Следующий шаг — загрузить env и проверить:")
    typer.echo("")
    typer.echo(f"  set -a && source {env_path} && set +a")
    typer.echo("  python -m digest_core.cli diagnose")
    typer.echo("")
